[server]
protocol = http
http_port = 3000
domain = localhost

[security]
admin_user = admin
admin_password = admin

[log]
mode = console
level = info

# To start Grafana with :
# docker run -d \
#  --name grafana \
#  -p 3000:3000 \
#  -v "$(pwd)/grafana.ini":/etc/grafana/grafana.ini \
#  grafana/grafana